# Dependencies 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            YUST
tagline:          'For YU statistics students'
description:      '영남대학교 통계학과 학생들에게 정보를 공유하기 위하여 만들었습니다. 유용하고 재밌는 이야기들을 찾아보길 바랍니다.'
url:              http://ksublee.github.io

author:
  name:           'Kyungsub Lee'
  url:            

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           

# Gems
gems: [jekyll-paginate]
